### **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

In [3]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
b = a.reshape(2, 6)
c = a.reshape (3, 4)
d = a.reshape (4, 3)
e = a.reshape (6, 2)
f = a.reshape (12, 1)

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [12]:
g = a.reshape(1, -1)
g = a.reshape(3, -1)
g = a.reshape(-1, 4)
g = a.reshape(-1, 6)
g = a.reshape(-1, 2)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [18]:
x = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
z = x.reshape (1,12)
x.ndim == z.ndim

False

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [29]:
g = np.random.randn(3, 4)
h = g.flatten()
g.size == h.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [47]:
a = np.arange(20, 0, -2)
a.ndim, a.shape, a.size

(1, (10,), 10)

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [48]:
b = np.arange(20, 1, -2)
b.reshape(1, 10)
b.ndim, b.shape, b.size

(1, (10,), 10)

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [53]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis=0)
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [73]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
B.shape, B.size

((4, 4), 16)

In [75]:
np.linalg.det(B) 

0.0

Нельзя вычислить обратную матрицу.
Обратную матрицу можно посчитать только для матрицы, определитель которой не равен 0. 
В данном случае определитель равен 0.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [79]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [88]:
c = np.random.randint(0, 16, 16)
c

array([15, 12,  1, 11,  9, 13,  2,  0,  7, 14,  2, 11,  9,  6,  9,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [92]:
C = c.reshape(4, 4)
C


array([[15, 12,  1, 11],
       [ 9, 13,  2,  0],
       [ 7, 14,  2, 11],
       [ 9,  6,  9,  4]])

In [93]:
D = C * 10 + B
D

array([[155, 134,  33, 142],
       [104, 180, 106, 122],
       [ 93, 226, 169, 322],
       [122, 182, 302, 342]])

In [94]:
np.linalg.det(D)

-514050600.0000002

In [97]:
np.linalg.matrix_rank(D)

4

In [99]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.0087675 , -0.00112503, -0.00700628,  0.00335757],
       [-0.00466612,  0.00935102,  0.00359743, -0.0047854 ],
       [-0.00387273,  0.00464343, -0.00563754,  0.0052594 ],
       [ 0.00277533, -0.00867529,  0.00556307, -0.0003714 ]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [103]:
D_inv = np.where (D_inv < 0, 0, 1)
D_inv

array([[1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [104]:
print(f'B : \n{B}\n\n C : \n{C}')

B : 
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

 C : 
[[15 12  1 11]
 [ 9 13  2  0]
 [ 7 14  2 11]
 [ 9  6  9  4]]


In [105]:
E = np.where(D_inv > 0, B, C)
print(E)

[[  5  12   1  32]
 [  9  50  86   0]
 [  7  86   2 212]
 [ 32   6 212   4]]
